version: "3"
networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - .:/var/www/app:delegated
    depends_on:
      - laravel
    networks:
      - laravel

  laravel:
    env_file: './.docker.env'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    links:
      - mysql
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql
      - phpmyadmin
    expose:
      - "9000"
      # volumes:
      # - .:/var/www/app:delegated
    networks:
      - laravel

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db_name'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3306
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - laravel

volumes:
  mysql_data:
